name: Build EXE

on:
  push:
    tags:
      - "v*" # e.g., v1.0, v2.0.1

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'pip' # Cache pip dependencies

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create dummy assets directory if it doesn't exist
        # Ensures PyInstaller doesn't fail if assets folder is empty or not yet created
        run: |
          if (-not (Test-Path assets)) {
            New-Item -ItemType Directory -Force -Path assets
            Write-Host "Created dummy assets directory."
          } else {
            Write-Host "Assets directory already exists."
          }
        shell: pwsh

      - name: Build EXE with PyInstaller
        run: |  # ★★★ この行のインデントを修正しました ★★★
          pyinstaller --noconfirm --onefile --console --name SRTTranslator --add-data "assets:assets" --hidden-import=flet_desktop --hidden-import=pysrt main.py

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/SRTTranslator.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}